version: 2.1
orbs:
  android: circleci/android@2.1.2

workflows:
  test:
    jobs:
      - android/run-ui-tests:
          executor: 
            name: android/android-machine
            resource-class: xlarge
            tag: "2022.06.2"
          system-image: system-images;android-30;default;x86_64
          additional-emulator-args: "-qemu -machine virt"
          wait-for-emulator: false
          # checkout: false
          post-emulator-launch-assemble-command: ""